name: Convert WebP to JPG in S3

on:
  workflow_dispatch:

jobs:
  convert-images:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Setup Node.js
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run the conversion script
    - name: Run WebP to JPG conversion script
      env:
        AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        NEXT_CONTINUATION_TOKEN: ${{ secrets.NEXT_CONTINUATION_TOKEN }}
      run: node index.js